### ISSUE TITLE
Missing Microsoft edge browser

### ISSUE THREAD

**Issue by stevemao** [cht8687/You-Dont-Need-Lodash-Underscore#11]
Microsoft is killing IE and Chakra is getting a lot of attention now :)

**Comment by cht8687** [comment]
That's why those functions can be used as most of the methods are IE9+... : )

**Comment by cht8687** [comment]
I will make edge version later or if you can help to add in that would be awesome.

**Comment by lewisje** [comment]
Those features available in any version of IE are also clearly available in Edge, but it's not so obvious whether those features never available in IE are now available in Edge; I think I'll look up which features Edge supports that IE does not.

**Comment by cht8687** [comment]
@lewisje  I think most of them are targeting IE9+. But we can still use https://github.com/es-shims/es5-shim for old browsers.

**Comment by lewisje** [comment]
I just looked it up: Edge supports `find` and `findIndex` (from ES6), but `includes` (stage 4 ES7 candidate) is still under consideration, and all of the other methods are already available at least as far back as IE9.

**Comment by wilmoore** [comment]
Similarly, would be great to mention Node.js. I know it's implied, but for those that don't use it everyday, it could help.

**Comment by lewisje** [comment]
Much like Edge, Node supports the ES5 and ES6 features in that list, but not the ES7 Stage 4 candidate, `Array#includes` (Kangax's ES7 table didn't include Node 5, however).

**Comment by stevemao** [comment]
> would be great to mention Node.js

Maybe phantomjs too? I say as many platforms as possible.

**Comment by cht8687** [comment]
@stevemao phantomjs 2.0 support most of the methods.

**Comment by cht8687** [comment]
@wilmoore  as far as I know, V8 implements all of ES5 methods.
