### ISSUE TITLE
Show complex use-cases

### ISSUE THREAD

**Issue by stevemao** [cht8687/You-Dont-Need-Lodash-Underscore#12]
```js
  _.each([1, 2, 3], function(value, index) {
    console.log(value);
  });
```
is simple use-case only
what about 
```js
  _.each([1, 2, 3], function(value, index) {
    ...
    return false;
  });
```

**Comment by cht8687** [comment]
I think keep it simple and clean is important. But complex use-cases are also fine I think.

**Comment by stevemao** [comment]
The reason is `Array.prototype.forEach` does not support `return false` to end loop as `_.each` do. 
Also `_.each` is faster as it's a stripped down version of `Array.prototype.forEach`. So the equivalent should be a `for` loop with `break`.

**Comment by bholben** [comment]
I really like the list.  I'm putting together a similar blog series about how/where to use Lodash.  My background is with some larger, computationally intensive applications, so my perspective may be a little different.  Reading this makes me want to add some details about when the Lodash investment is worth it and when it is not.  Here's my summary of some advantages of the Lodash looping constructs vs. the built-ins...  http://www.bholben.com/blog/lodash-is-superior-to-array-prototype-loops/

**Comment by cht8687** [comment]
Hi @bholben that's a really nice article for comparing the difference between the two! Many thanks to share it here.
