### ISSUE TITLE
Include version support with polyfill

### ISSUE THREAD

**Issue by Alex-Sokolov** [cht8687/You-Dont-Need-Lodash-Underscore#16]
Maybe add version support for browsers with polyfill (https://github.com/es-shims/es5-shim)?

**Comment by cht8687** [comment]
Thank you @Alex-Sokolov. Definitely es5-shim should be mentioned. I am just thinking about how to add it in. Maybe just point out that, for older browsers, we can use es5-shim. I really want to keep the list mainly for native support without any other third party dependencies or shims. : )

**Comment by cht8687** [comment]
@Alex-Sokolov I had added es5-shim link.
