### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by BBCMarkMcDonnell** [cht8687/You-Dont-Need-Lodash-Underscore#17]
Hello,

Just a quick comment that @jdalton (Microsoft) has investigated the performance implications of using native over abstraction libraries and it appears native is generally slower.

I think it would be worth making note of this within your README as it's otherwise a bit misleading. 

Thanks

**Comment by jdalton** [comment]
I don't think there's a need to qualify the post as [most get it](https://www.reddit.com/r/javascript/comments/42quf8/youdontneedlodashunderscore/). The title is click bait but the gist is correct. If you're only using a handful of methods, on arrays only, and don't care about nullish guards, smoothing over environment issues or ES5/ES6 issues, iteratee shorthands, & lazy evaluation then built-ins are great. Folks who use lodash know it works great combo'ed with ES6 and can cleanup their code beyond what's doable with built-ins.

**Comment by cht8687** [comment]
@BBCMarkMcDonnell, Hi Mark, yes you are quite right about the performance. That's why I've fixed the word to remove the claim that native is faster. https://github.com/cht8687/You-Dont-Need-Lodash-Underscore/commit/7d7147369096fec2e2ab273e21210c38454725b4 @jdalton Great to know the goodies of Lodash. : ) I've learned a lot through you guys. Cheers.

**Comment by cht8687** [comment]
@jdalton Again John, thank you for your hard work on Lodash which makes our developers' lives easier. It is invaluable treasure for our developers.

**Comment by Integralist** [comment]
Cool. Thanks for the feedback

**Comment by stevemao** [comment]
I have created [You-Dont-Know-About-Lodash-Underscore](https://github.com/stevemao/You-Dont-Know-About-Lodash-Underscore) which contains performance an differences between lodash/underscore and native methods.

**Comment by jdalton** [comment]
> I have created You-Dont-Know-About-Lodash-Underscore which contains performance an differences between lodash/underscore and native methods.

I appreciate the sentiment but getting pushing static micro benchmark results isn't that great either. I'm a fan of built-ins. As the Chakra performance PM I pushed-to and succeeded-in optimizing a few of them. For more on lodash and performance see my [ThunderPlains deep dive into Lodash and JS performance](https://www.youtube.com/watch?v=OP8jdbcDfaA).

**Comment by cht8687** [comment]
@stevemao Thank you for that, but the main purpose for this list is for reminding our developers that, what methods are already native supported. 

@jdalton 
for your statement that:
>If you're only using a handful of methods on arrays and don't care about nullish guards, object iteration, smoothing over enviro/ES5/ES6 issues, FP goodies, iteratee shorthands, lazy evaluation, or other enhancements then built-ins are the way to go. Folks who use lodash know its 270+ modules work great combo'ed with ES6, enabling cleaner code and empowering beyond built-ins.

Yes you are absolutely right. But, in case I want more complex methods, my personal choice is [Immutable.js](https://facebook.github.io/immutable-js/), I like the performance of immutable.js in some of my Redux + React projects. I am not sure about what @gaearon 's opinion about this, but personally, I find Immutable.js as a whole is more convenient for me to gain predictability through immutability than Lodash.

**Comment by jdalton** [comment]
> Yes you are absolutely right. But, in case I want more complex methods, my personal choice is Immutable.js, I like the performance of immutable.js in some of my Redux + React projects.

Lodash and Immutable are a bit different. Lodash is a generic utility library and has a wider range of methods and scenarios it caters to. That said, Lodash does offer immutable methods with its `fp` build. Using `require('lodash/fp')` provides immutable auto-curried iteratee-first data-last flavors of lodash methods.

**Comment by jdalton** [comment]
It would be great if you could follow up on https://github.com/cht8687/You-Dont-Need-Lodash-Underscore/pull/21#issuecomment-176665256. As your project is currently a bit misleading.

**Comment by cht8687** [comment]
@jdalton I've included [disclaimer](https://github.com/cht8687/You-Dont-Need-Lodash-Underscore/commit/e8ebad33b8c5dfe561ae0323fd7441e19d646a40), let me know if you'd like any more changes regarding this issue.

**Comment by jdalton** [comment]
>  I've included disclaimer, let me know if you'd like any more changes regarding this issue.

That's perfect!

**Comment by jdalton** [comment]
Thank you!
