### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by devanp92** [cht8687/You-Dont-Need-Lodash-Underscore#18]
Is there a roadmap for this project to display which functions to implement?

**Comment by cht8687** [comment]
Hi @devanp92, this project doesn't plan to implement functions. It will have a handy collection of native methods for those who want less dependencies in their projects. But if you have any plans which can make this list better, just feel free to contribute to it. Thanks!!

**Comment by devanp92** [comment]
Great! Is there a need for the function .join()?

**Comment by cht8687** [comment]
@devanp92  Yes. But since it is a Lodash only function, just label it as Lodash only function in this format: https://github.com/cht8687/You-Dont-Need-Lodash-Underscore#_reverse
