### ISSUE TITLE
Missing Object.assign() for _.extend/assign

### ISSUE THREAD

**Issue by kotarou3** [cht8687/You-Dont-Need-Lodash-Underscore#32]
Doesn't match behaviour *exactly* IIRC, but matches close enough for most people's use cases

**Comment by cht8687** [comment]
@kotarou3 That sounds good. Welcome PR. :smile:

**Comment by pmcelhaney** [comment]
Looks like this is done so it can be closed.

**Comment by cht8687** [comment]
thank you!
