### ISSUE TITLE
Enforce a consistent code style

### ISSUE THREAD

**Issue by dracupid** [cht8687/You-Dont-Need-Lodash-Underscore#34]
I found some inconsistencies in the code style, especially the space around infix operators.
```js 
return element >=10;
return value*2;
return value >= 10;
```
I think that it will be better to enforce a consistent style in this project, such as [JavaScript Standard Style](http://standardjs.com/) or anything else.

**Comment by cht8687** [comment]
hi @dracupid, thank you for pointing it out. I will look into this issue.
