### ISSUE TITLE
reduceRight native example is wrong

### ISSUE THREAD

**Issue by ifrim** [cht8687/You-Dont-Need-Lodash-Underscore#4]
var array = [0, 1, 2, 3, 4];
    var result = array.reduce(function (previousValue, currentValue, currentIndex, array) {
        return previousValue - currentValue;
    });
    console.log(result);
    // output: -2

The above output is not "-2" it is "-10".

**Comment by cht8687** [comment]
oh thank for that! @ifrim I am correcting it now.
