### ISSUE TITLE
To John-David Dalton ( Lodash creator) 

### ISSUE THREAD

**Issue by cht8687** [cht8687/You-Dont-Need-Lodash-Underscore#55]
Dear John @jdalton,

I respect your work of Lodash.
I took your suggestions to put in [quotes](https://github.com/cht8687/You-Dont-Need-Lodash-Underscore/commit/e8ebad33b8c5dfe561ae0323fd7441e19d646a40) as you requested in my repo.
I included your comments as well as [voice of expert](https://github.com/cht8687/You-Dont-Need-Lodash-Underscore/commit/94ebbc7ffbfb9a72a688d24d91d7c694ea80b39c).
When you laughed at me earlier this year, I was just a bit sad.(https://twitter.com/jdalton/status/693975347717496832) 
But when you start to harass our collaborator @stevemao [ screenshot provided below ], I am more than sad now. 
Why you such a guy always willing to stop people doing what they like? Is this how Lodash being built? is this why it has a 'low' in it's name?
I see so many of your attempts trying to 'attack' people who hold different opinions with you.
Why you are such a  MEAN guy!!!
Remember that:
You 'created' Lodash based on [Jeremy's](https://github.com/jashkenas) work, if I were you I will never feel proud of it.
If I were you, I will use all my time on improving Chakra Engine which you claims you are working on. Can you sleep well that [Edge](https://www.netmarketshare.com/browser-market-share.aspx?qprid=2&qpcustomd=0) only has 4% market shares? You can do it mate.

![photo 3-07-2016 1 08 39 pm](https://cloud.githubusercontent.com/assets/4587603/16543599/df9a2702-411f-11e6-8788-e6ea72a29923.jpg)

**Comment by jdalton** [comment]
Hey @cht8687.

It wasn't harassment. It was a private message asking if I'd don't something to prompt a change of heart as @stevemao also created [You-Dont-Know-Lodash-Underscore](https://github.com/stevemao/You-Dont-Know-Lodash-Underscore) is all. Thanks for doing what you do though.

**Comment by cht8687** [comment]
@jdalton  Thank you for referencing my HN post as well. You are amazing to 
find out every corner on the internet where there is a finger pointing at you. :smile: 

You beat me John. You are the best person in the world. Lodash is the best JavaScript library in the world! :beers:
