### ISSUE TITLE
Disallow aliases

### ISSUE THREAD

**Issue by pmcelhaney** [cht8687/You-Dont-Need-Lodash-Underscore#58]
_ libraries sometimes provide the exact same function under multiple names, e.g. [each/forEach](https://lodash.com/docs#forEach).

The ESLint plugin should have options to require the use of one particular alias over the others.

```js 
   /*eslint you-dont-need-lodash-underscore/forEach: ["error", { preferNative: "never", alias: "forEach" }]*/

    // invalid
    _.each([1,2,3], fn);
   
   // valid
   _.forEach([1,2,3], fn);
```

**Comment by stevemao** [comment]
I think this is out of the scope of this module.

**Comment by cht8687** [comment]
so Pat, are we helping to make a Lodash-Lint now? or just combine with both native alternatives with Lodash suggestions together?

**Comment by pmcelhaney** [comment]
Do'h. Didn't know that was a thing. :)

**Comment by cht8687** [comment]
This is a cool idea, I vote it.
